# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: u:/Xilinx/Projects/2018_demo_gamma_1/vivado_proj/Zybo-Z7-20-HDMI.srcs/sources_1/bd/design_1/ip/design_1_hls_saturation_enhan_0_0/design_1_hls_saturation_enhan_0_0.xci
# IP: The module: 'design_1_hls_saturation_enhan_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/Xilinx/Projects/2018_demo_gamma_1/vivado_proj/Zybo-Z7-20-HDMI.srcs/sources_1/bd/design_1/ip/design_1_hls_saturation_enhan_0_0/constraints/hls_saturation_enhance_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_hls_saturation_enhan_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: u:/Xilinx/Projects/2018_demo_gamma_1/vivado_proj/Zybo-Z7-20-HDMI.srcs/sources_1/bd/design_1/ip/design_1_hls_saturation_enhan_0_0/design_1_hls_saturation_enhan_0_0.xci
# IP: The module: 'design_1_hls_saturation_enhan_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/Xilinx/Projects/2018_demo_gamma_1/vivado_proj/Zybo-Z7-20-HDMI.srcs/sources_1/bd/design_1/ip/design_1_hls_saturation_enhan_0_0/constraints/hls_saturation_enhance_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_hls_saturation_enhan_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
